module.exports.getJobList = require('./listJob.services')
module.exports.addJobProcess = require('./addJobProcess.service')
module.exports.getJobById = require('./getJobById.services')
module.exports.getJobByDocumentId = require('./getJobByDocumentId.services')
module.exports.getJobListWithOutLimit = require('./getJobWithOutLimit.services')