const { getAccessModulesFn } = require("../modules/auth/auth.service")

// ALL Module
VIEW_STATUS = "VIEW_STATUS"
ADD_NOTES = "ADD_NOTES"
DELETE_DOCUMENT = "DELETE_DOCUMENT"
DELETE_DOCUMENT_PAGE = "DELETE_DOCUMENT_PAGE"
REQUEST_TO_DELETE_DOCUMENT_PAGE = "REQUEST_TO_DELETE_DOCUMENT_PAGE"
MANAGE_DOCUMENT = "MANAGE_DOCUMENT"
UPDATE_LOGIC = "UPDATE_LOGIC"
DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
UPDATE_FIELD = "UPDATE_FIELD"
ASSIGN_TO = "ASSIGN_TO"
REUPLOAD_PDF = "REUPLOAD_PDF"
VIEW_RAW = "VIEW_RAW"
SYNC_WITH_ERP = "SYNC_WITH_ERP"
EXTRACTION = "EXTRACTION"
VIEW_DOCUMENT = "VIEW_DOCUMENT"
VIEW_DOCUMENT_PAGE = "VIEW_DOCUMENT_PAGE"
EXPORT_DOCUMENTS = "EXPORT_DOCUMENTS"
ALLOW_SYNCHRONIZATION = "ALLOW_SYNCHRONIZATION"
MANAGE_USER = "MANAGE_USER"
ADD_USER = "ADD_USER"
EDIT_USER = "EDIT_USER"
VIEW_USER = "VIEW_USER"
MANAGE_ROLE = "MANAGE_ROLE"
ADD_ROLE = "ADD_ROLE"
ADD_USERS = "ADD_USERS"
EDIT_ROLE = "EDIT_ROLE"
DELETE_ROLE = "DELETE_ROLE"
SHIPPING_LINE = "SHIPPING_LINE"
ADD_SHIPPING_LINE = "ADD_SHIPPING_LINE"
EDIT_SHIPPING_LINE = "EDIT_SHIPPING_LINE"
DELETE_SHIPPING_LINE = "DELETE_SHIPPING_LINE"
CONTAINER_ISO_CODE = "CONTAINER_ISO_CODE"
ADD_CONTAINER_ISO_CODE = "ADD_CONTAINER_ISO_CODE"
EDIT_CONTAINER_ISO_CODE = "EDIT_CONTAINER_ISO_CODE"
DELETE_CONTAINER_ISO_CODE = "DELETE_CONTAINER_ISO_CODE"
AIR_PORT_MASTERS = "AIR_PORT_MASTERS"
ADD_AIR_PORT_MASTERS = "ADD_AIR_PORT_MASTERS"
EDIT_AIR_PORT_MASTERS = "EDIT_AIR_PORT_MASTERS"
DELETE_AIR_PORT_MASTERS = "DELETE_AIR_PORT_MASTERS"
PORT_MASTERS = "PORT_MASTERS"
ADD_PORT_MASTERS = "ADD_PORT_MASTERS"
EDIT_PORT_MASTERS = "EDIT_PORT_MASTERS"
DELETE_PORT_MASTERS = "DELETE_PORT_MASTERS"
MANAGE_DOMAIN = "MANAGE_DOMAIN"
ADD_DOMAIN = "ADD_DOMAIN"
EDIT_DOMAIN = "EDIT_DOMAIN"
DELETE_DOMAIN = "DELETE_DOMAIN"
DELETE_REQUEST = "DELETE_REQUEST"
AIR = "AIR"
OCEAN = "OCEAN"
VIEW_ALL_DOCUMENTS_ACCESS = "VIEW_ALL_DOCUMENTS_ACCESS"

// Default Access
MANAGE_DASHBOARD = "MANAGE_DASHBOARD"
VIEW_DASHBOARD = "VIEW_DASHBOARD"

// Super Admin Only 
FIELD_MAPPING = "FIELD_MAPPING"
LABEL_MATRIX = "LABEL_MATRIX"
CUSTOM_LOGIC = "CUSTOM_LOGIC"
FIELDS = "FIELDS"

async function hasAccess(module, user) {
    const {role,accessModules} = await getAccessModulesFn(user.roleId)
    if (role == "superAdmin") {
        return true
    }else{
        return accessModules.includes(module)
    }
}

module.exports ={
    hasAccess,
    VIEW_ALL_DOCUMENTS_ACCESS,
    VIEW_STATUS,
    ADD_NOTES,
    DELETE_DOCUMENT,
    DELETE_DOCUMENT_PAGE,
    REQUEST_TO_DELETE_DOCUMENT_PAGE,
    MANAGE_DOCUMENT,
    UPDATE_LOGIC,
    DOCUMENT_UPLOAD,
    UPDATE_FIELD,
    ASSIGN_TO,
    REUPLOAD_PDF,
    VIEW_RAW,
    SYNC_WITH_ERP,
    EXTRACTION,
    VIEW_DOCUMENT,
    VIEW_DOCUMENT_PAGE,
    EXPORT_DOCUMENTS,
    ALLOW_SYNCHRONIZATION,
    MANAGE_USER,
    ADD_USER,
    EDIT_USER,
    VIEW_USER,
    MANAGE_ROLE,
    ADD_ROLE,
    ADD_USERS,
    EDIT_ROLE,
    DELETE_ROLE,
    SHIPPING_LINE,
    ADD_SHIPPING_LINE,
    EDIT_SHIPPING_LINE,
    DELETE_SHIPPING_LINE,
    CONTAINER_ISO_CODE,
    ADD_CONTAINER_ISO_CODE,
    EDIT_CONTAINER_ISO_CODE,
    DELETE_CONTAINER_ISO_CODE,
    AIR_PORT_MASTERS,
    ADD_AIR_PORT_MASTERS,
    EDIT_AIR_PORT_MASTERS,
    DELETE_AIR_PORT_MASTERS,
    PORT_MASTERS,
    ADD_PORT_MASTERS,
    EDIT_PORT_MASTERS,
    DELETE_PORT_MASTERS,
    MANAGE_DOMAIN,
    ADD_DOMAIN,
    EDIT_DOMAIN,
    DELETE_DOMAIN,
    DELETE_REQUEST,
    AIR,
    OCEAN,
    MANAGE_DASHBOARD,
    VIEW_DASHBOARD,
    FIELD_MAPPING,
    LABEL_MATRIX,
    CUSTOM_LOGIC,
    FIELDS,
}